version: "3.8"

services:
  elgg:
    image: bitaouioussama/elgg-app:latest
    container_name: elgg-app
    depends_on:
      - db
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - elgg_data:/var/elgg_data
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: elgg-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: elgg-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env

volumes:
  db_data:
  elgg_data:
