version: "3.8"

services:
  elgg:
    image: bitaouioussama/elgg-app:latest
    container_name: elgg-app
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - /var/elgg_data:/var/www/html/elgg/data

  db:
    image: mariadb:10.5
    container_name: elgg-db
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: elgg-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}

volumes:
  db_data:
