name: Build and Push Elgg Docker Image

on:
  push:
    branches:
      - master

    paths:
      - 'Dockerfile'
      - 'src/**'
      - '000-default.conf'
      - 'docker-compose.yml'

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull previous image for cache (ignore error if image does not exist)
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/elgg-app:latest || true

      - name: Build Docker image using cache
        run: |
          docker build \
            --cache-from=${{ secrets.DOCKERHUB_USERNAME }}/elgg-app:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/elgg-app:latest \
            .

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/elgg-app:latest
